In [1]:
import torch

In [2]:
t1=torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
t2=torch.tensor([[2,3],[4,5],[6,7]])
t2

tensor([[2, 3],
        [4, 5],
        [6, 7]])

In [11]:
t3=torch.tensor([
    [[1,2,3],
     [3,4,5],
     [5,6,7],
     [7,8,9],]])
t3.dtype

torch.int64

In [15]:

print(t3.shape)

torch.Size([3, 2])
torch.Size([1, 4, 3])


Tensor Operations and Gradients...

In [16]:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [18]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [19]:
# Compute Derivatives
y.backward()

In [21]:
##Display Gradients...
print('dy/dx: ',x.grad)
print('dy/dw: ',w.grad)
print('dy/db: ',b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


InterProbability with NumPy...


In [22]:
import numpy as np

In [23]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [24]:
y=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9],
             [10,11,12]]])
y

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

*LinearRegression...*