<a href="https://colab.research.google.com/github/i-am-parker01/BasicsPyTorch/blob/main/Tensor_DataTypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""
floating- used for deep-learning tasks--->>> float32, float64, float16
Integers- For categorical data and indices.--->>> int32, int64, int8
booleans- Mask/Logical Operations.
Complex Numbers- Used for advanced Computation.--->>> complex64, complex128.

Memory Consumption : float16 << float32 << float64
Computation: Lower Precision will be faster on GPU...
numerical Precision: float64 is more precise than float32
"""

'\nfloating- used for deep-learning tasks.\nIntegers- For categorical data and indices.\nbooleans- Mask/Logical Operations.\nComplex Numbers- Used for advanced Computation..\n'

In [2]:
import torch

In [4]:
default_tensor=torch.tensor([1.5,2.5,3.5])
print(default_tensor.dtype)

torch.float32


In [5]:
float_tensor=torch.tensor([1.5,5.7,6.9],dtype=torch.float64)
print(float_tensor.dtype)

torch.float64


In [6]:
float_tensor3=torch.tensor([1.5,5.7,6.8],dtype=torch.float16)
print(float_tensor3.dtype)

torch.float16


In [7]:
int_value=torch.tensor([1,2,3])
print(int_value.dtype)

torch.int64


In [8]:
int_value2=torch.tensor([2,6,7],dtype=torch.int8)
print(int_value2.dtype)

torch.int8


In [10]:
complex=torch.tensor([1+2j])
print(complex.dtype)

torch.complex64


In [11]:
complex2=torch.tensor([7+9j],dtype=torch.complex128)
print(complex2.dtype)

torch.complex128


In [13]:
randoms=torch.tensor([1.8,5.9,2.8],dtype=torch.int32)
print(randoms.dtype)
print(randoms)

torch.int32
tensor([1, 5, 2], dtype=torch.int32)


In [16]:
booleans=torch.tensor([True,False,True],dtype=torch.bool)
print(booleans.dtype)
print(booleans)

torch.bool
tensor([ True, False,  True])


In [22]:
float_tensor=torch.tensor([1.5,2.5,3.5])
print(float_tensor.dtype)
print(float_tensor)

int_tensor=float_tensor.to(torch.int64)
print(int_tensor.dtype)
print(int_tensor)

torch.float32
tensor([1.5000, 2.5000, 3.5000])
torch.int64
tensor([1, 2, 3])


In [24]:
bool_tensor1=int_tensor.to(torch.bool)
print(bool_tensor1.dtype)
print(bool_tensor1)

torch.bool
tensor([True, True, True])


In [25]:
complex_tensor=float_tensor.to(torch.complex128)
print(complex_tensor.dtype)
print(complex_tensor)

torch.complex128
tensor([1.5000+0.j, 2.5000+0.j, 3.5000+0.j], dtype=torch.complex128)


In [26]:
int=torch.tensor([0,1,5,0])
bool=int.to(torch.bool)
print(bool.dtype)
print(bool)

torch.bool
tensor([False,  True,  True, False])


In [28]:
float=torch.tensor([1.7,5.9,0,5.])
boolean=float.to(torch.bool)
print(boolean.dtype)
print(boolean)

torch.bool
tensor([ True,  True, False,  True])


**Impact of data type on memory...**

In [31]:
float_tensor1=torch.ones(1000,dtype=torch.float32)
float_tensor2=torch.ones(1000,dtype=torch.float64)
float_tensor3=torch.ones(1000,dtype=torch.float16)
#Tensor element size...
# element_size-->> gives the size of one element in bytes..
# nelements-->>> Returns total number of elements in an array....
print("Memory used by float32 tensor: ",float_tensor1.element_size()* float_tensor1.nelement())
print("Memory used by float64 tensor: ",float_tensor2.element_size()* float_tensor2.nelement())
print("Memory used by float16 tensor: ",float_tensor3.element_size()*float_tensor3.nelement())


Memory used by float32 tensor:  4000
Memory used by float64 tensor:  8000
Memory used by float8 tensor:  2000
